Fixes an issue where installing on top of this requires sudo
```
gem install bundler
Fetching: bundler-1.16.0.gem (100%)
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /usr/local/bundle/cache/bundler-1.16.0.gem
```

cc #99